This project has been running since 2003 in partnership with the European Union, ICEP (an Austrian NGO) and the Austrian government in villages in Kiambu and Kajiado District. The aim of the project is to empower women through basic business training with the help of university students. The university students are trained and they in turn go to the villages and train the women. The training includes sessions on how to run a business well:
●	planning
●	budgeting 
●	accounts 
●	marketing
●	viability and savings 
Each student takes charge of helping a small group of women to plan their own businesses. To date 1939 women have gone through this program. Most of the enterprises started by the women are flourishing with over 60% of them having more than doubled their monthly income.
The students, under the supervision of the project coordinator, monitor the women for six months to help them solve any problems that may arise, study initiatives, and evaluate possibilities for future expansion. Additionally, Kianda Foundation puts the women in contact with micro-finance programs and helps them to get loans to improve their businesses. The women who attend the TOT program value it highly, because they learn to run their businesses with professional standards, and improve their standard of living. They also appreciate the life skills that are taught as part of the course; such as nutrition and cookery, inter-personal relationships, self- esteem, health, HIV/AIDS, good upbringing of children, etc. All these have a positive effect on the whole family.
Most of the university students find that participating in the TOT project helps them to work with a professional mentality. They have learnt to make better use of their time, to work diligently and constantly, and to be responsible about the things they have undertaken. They comment that they would like to give a social dimension to their jobs, for example by introducing specific community development initiatives in the organizations they will work in after graduating.
Education and access to the means of economic emancipation are key to the success of the women. Women need to be able to raise loans and gain the necessary knowledge to improve their business productivity. Micro-financing is a way of helping women who have repeatedly proved their capacity to repay loans. Lack of opportunities is one of the characteristics of people living in conditions of extreme poverty. We want women to be at the forefront of economic growth.

